"""
model.py — Step 2: Classifier

Loads outputs/features.csv, drops the dead EXIF features (near-zero variance
in this dataset), scales the remaining numeric features, and evaluates two
simple classifiers using Leave-One-Out Cross-Validation (LOOCV) -- the right
choice at small n, since a train/test split this small would be close to
meaningless.

Also supports outputs/video_features.csv (temporal-consistency features from
features.py's video path) via the same run_loocv() function -- no new
evaluation logic needed, just a different feature set fed in.

Prints:
  - LOOCV accuracy for both models (image set, and video set if present)
  - Confusion matrix for both models
  - Logistic regression coefficients (which features it leans on, and which
    direction)
  - Random forest feature importances (for comparison)

Also fits FINAL models on all data (for use by ai.py / dashboard downstream)
and saves per-image / per-video LOOCV predictions to outputs/predictions.csv
and outputs/video_predictions.csv.

Run from project root:
    python3 src/model.py
"""

import os
import numpy as np
import pandas as pd
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FEATURES_CSV = os.path.join(PROJECT_ROOT, "outputs", "features.csv")
VIDEO_FEATURES_CSV = os.path.join(PROJECT_ROOT, "outputs", "video_features.csv")
PREDICTIONS_CSV = os.path.join(PROJECT_ROOT, "outputs", "predictions.csv")
VIDEO_PREDICTIONS_CSV = os.path.join(PROJECT_ROOT, "outputs", "video_predictions.csv")
MODEL_ARTIFACT = os.path.join(PROJECT_ROOT, "outputs", "model_artifacts.joblib")
VIDEO_MODEL_ARTIFACT = os.path.join(PROJECT_ROOT, "outputs", "video_model_artifacts.joblib")

# Features confirmed useful (has_exif / has_camera_tag dropped: near-zero
# variance across this dataset -- see write-up notes).
FEATURE_COLS = ["fft_hf_ratio", "ela_variance", "ela_mean", "noise_perfection_score"]
LABEL_COL = "label"

# Video feature set: per-frame means + temporal (frame-to-frame) variance,
# for each of the same four base signals. Generated by features.py's
# video_temporal_features(). New signal is the *_temporal_var columns --
# those didn't exist in the image-only pipeline.
VIDEO_FEATURE_COLS = [
    "fft_hf_ratio_mean", "fft_hf_ratio_temporal_var",
    "ela_variance_mean", "ela_variance_temporal_var",
    "ela_mean_mean", "ela_mean_temporal_var",
    "noise_perfection_score_mean", "noise_perfection_score_temporal_var",
]


def load_data(csv_path, feature_cols):
    """Generic loader -- used for both image and video feature sets."""
    df = pd.read_csv(csv_path)
    X = df[feature_cols].values
    y = (df[LABEL_COL] == "fake").astype(int).values  # 1 = fake, 0 = real
    return df, X, y


def run_loocv(model_name, model_builder, X, y):
    """
    Runs Leave-One-Out CV. model_builder is a zero-arg function that returns
    a fresh, unfitted model each fold. Scaler is refit per-fold too, so no
    data leaks between folds. Same function serves image and video feature
    sets -- LOOCV logic doesn't care what the columns represent.
    """
    loo = LeaveOneOut()
    y_true, y_pred, y_proba = [], [], []

    for train_idx, test_idx in loo.split(X):
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled = scaler.transform(X_test)

        model = model_builder()
        model.fit(X_train_scaled, y_train)

        pred = model.predict(X_test_scaled)[0]
        proba = model.predict_proba(X_test_scaled)[0][1]  # P(fake)

        y_true.append(y_test[0])
        y_pred.append(pred)
        y_proba.append(proba)

    y_true, y_pred, y_proba = np.array(y_true), np.array(y_pred), np.array(y_proba)

    acc = accuracy_score(y_true, y_pred)
    n_correct = int(np.sum(y_true == y_pred))  # direct count -- avoids float-rounding
                                                 # edge cases from int(acc*len(y))
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec = recall_score(y_true, y_pred, zero_division=0)
    cm = confusion_matrix(y_true, y_pred)

    print(f"\n--- {model_name} (LOOCV, n={len(y)}) ---")
    print(f"Accuracy:  {acc:.3f}  ({n_correct}/{len(y)} correct)")
    print(f"Precision (fake): {prec:.3f}")
    print(f"Recall (fake):    {rec:.3f}")
    print("Confusion matrix (rows=true, cols=predicted, order=[real, fake]):")
    print(cm)
    print("Full report (both classes):")
    print(classification_report(y_true, y_pred, target_names=["real", "fake"], zero_division=0))

    return y_pred, y_proba


def print_logreg_coefficients(X, y, feature_cols):
    """
    Fits logistic regression on ALL data (not CV) purely to inspect which
    features it leans on and in which direction. Diagnostic only -- fitting
    on all rows overstates confidence, but useful to show HOW the model
    reasons.
    """
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    model = LogisticRegression(max_iter=1000)
    model.fit(X_scaled, y)

    print("\n--- Logistic Regression coefficients ---")
    print("(Positive = pushes toward 'fake', negative = pushes toward 'real')")
    for feat, coef in zip(feature_cols, model.coef_[0]):
        print(f"  {feat:32s} {coef:+.3f}")


def print_rf_importances(X, y, feature_cols):
    """
    NOTE: fits on RAW (unscaled) X, unlike logreg. Tree splits are invariant
    to monotonic feature scaling, so RF importances are identical either
    way. Logreg coefficients, by contrast, are meaningless without scaling.
    Don't "fix" this to match logreg -- it changes nothing for RF.
    """
    model = RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42)
    model.fit(X, y)

    print("\n--- Random Forest feature importances ---")
    for feat, imp in zip(feature_cols, model.feature_importances_):
        print(f"  {feat:32s} {imp:.3f}")


def train_and_save(csv_path, feature_cols, predictions_csv, model_artifact, label):
    """
    Runs the full LOOCV + interpretability + final-fit-and-save pipeline for
    one feature set (image or video). Returns True if it ran, False if the
    CSV didn't exist / was empty (video set is optional).
    """
    if not os.path.exists(csv_path):
        print(f"\n[{label}] No file at {csv_path} -- skipping (optional).")
        return False

    df, X, y = load_data(csv_path, feature_cols)
    if len(df) == 0:
        print(f"\n[{label}] {csv_path} is empty -- skipping.")
        return False

    print(f"\n{'='*70}\n[{label}] Loaded {len(df)} rows | real: {(y==0).sum()} | fake: {(y==1).sum()}")
    print(f"[{label}] Features used: {feature_cols}")

    logreg_pred, logreg_proba = run_loocv(
        f"{label} - Logistic Regression",
        lambda: LogisticRegression(max_iter=1000),
        X, y
    )
    rf_pred, rf_proba = run_loocv(
        f"{label} - Random Forest (shallow)",
        lambda: RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42),
        X, y
    )

    print_logreg_coefficients(X, y, feature_cols)
    print_rf_importances(X, y, feature_cols)

    # Fit FINAL models on all data for downstream scoring. LOOCV numbers
    # above (not this fit) are the honest generalization estimate.
    final_scaler = StandardScaler()
    X_scaled_all = final_scaler.fit_transform(X)

    final_logreg = LogisticRegression(max_iter=1000)
    final_logreg.fit(X_scaled_all, y)

    final_rf = RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42)
    final_rf.fit(X, y)  # RF trained on raw features -- see note above

    joblib.dump({
        "scaler": final_scaler,
        "logreg": final_logreg,
        "rf": final_rf,
        "feature_cols": feature_cols,
    }, model_artifact)
    print(f"\n[{label}] Saved final scaler + models to {model_artifact}")

    out_df = df[["filename", "label"]].copy()
    out_df["logreg_pred"] = np.where(logreg_pred == 1, "fake", "real")
    out_df["logreg_p_fake"] = logreg_proba
    out_df["rf_pred"] = np.where(rf_pred == 1, "fake", "real")
    out_df["rf_p_fake"] = rf_proba
    out_df["logreg_correct"] = out_df["label"] == out_df["logreg_pred"]
    out_df["rf_correct"] = out_df["label"] == out_df["rf_pred"]
    out_df.to_csv(predictions_csv, index=False)
    print(f"[{label}] Saved per-row LOOCV predictions to {predictions_csv}")

    misses = out_df[~out_df["logreg_correct"] | ~out_df["rf_correct"]]
    if len(misses) > 0:
        print(f"\n[{label}] {len(misses)} row(s) where at least one model was wrong:")
        print(misses[["filename", "label", "logreg_pred", "rf_pred"]].to_string(index=False))
    else:
        print(f"\n[{label}] Both models got every row right under LOOCV.")
        print(f"[{label}] At small n, treat a perfect score with suspicion, not celebration --")
        print(f"[{label}] more likely the signals are cleanly separable on THIS small set")
        print(f"[{label}] than that the approach generalizes.")

    return True


def main():
    os.makedirs(os.path.join(PROJECT_ROOT, "outputs"), exist_ok=True)

    # image pipeline -- unchanged behavior from before video support was added
    train_and_save(FEATURES_CSV, FEATURE_COLS, PREDICTIONS_CSV, MODEL_ARTIFACT, label="IMAGE")

    # video pipeline -- optional, runs only if outputs/video_features.csv exists
    train_and_save(VIDEO_FEATURES_CSV, VIDEO_FEATURE_COLS, VIDEO_PREDICTIONS_CSV,
                    VIDEO_MODEL_ARTIFACT, label="VIDEO")


if __name__ == "__main__":
    main()